### ISSUE TITLE
will this plugin  support other type of file like .js

### ISSUE THREAD

**Issue by Lorem3** [bennycode/hexo-insert-markdown#3]
like this 
\```
include Dir/a.js
\```

**Comment by bennycode** [comment]
No, if you want to include code in your articles I recommend using the official [codeblock](https://hexo.io/docs/tag-plugins.html#Code-Block) or [include_code](https://hexo.io/docs/tag-plugins.html#Include-Code) syntax. 

It can be used like this:

```
{% include_code lang:javascript my-code.js %}
```
