### ISSUE TITLE
it can't work on my environment

### ISSUE THREAD

**Issue by qiub649691422** [bennycode/hexo-insert-markdown#4]
![image](https://user-images.githubusercontent.com/23074909/138151984-ca178336-7901-41ab-a09a-3783fe5316ed.png)

**Comment by bennycode** [comment]
Hi @qiub649691422, which version of Hexo.js are you using?

**Comment by qiub649691422** [comment]
hexo version : 5.4.0
![image](https://user-images.githubusercontent.com/23074909/138182237-d9cfbe35-f18e-489f-95eb-0e9efcb6de04.png)
- My root Markdown file is located in source/_post/index.md
- I want to insert another file from source/_blog-draft/test/test.md.
- the tag in index.md is ``{% insertmd _blog-draft/test/test.md '---' %}``

**Comment by bennycode** [comment]
Hi @qiub649691422, please try again with **Hexo v6.1.0** and **hexo-insert-markdown v1.3.1**.  I just tested it and it works.🙂 

You can reopen this ticket if it doesn't work for you after updating the dependencies.
